name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev wget git

    - name: Download AOSP Toolchains
      run: |
        mkdir -p $GITHUB_WORKSPACE/tc
        cd $GITHUB_WORKSPACE/tc
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc64
        git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc32

    - name: Fix Taskstats Line 479
      run: |
        sed -i '479s/#elif/#else/' kernel/taskstats.c

    - name: Build Kernel
      run: |
        export PATH=$GITHUB_WORKSPACE/tc/gcc64/bin:$GITHUB_WORKSPACE/tc/gcc32/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        
        make O=out vendor/fog-perf_defconfig
        make -j$(nproc --all) O=out KCFLAGS="-w -D__NO_FORTIFY" WERROR=0
        
    - name: Upload Boot Image or Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Kernel
        path: out/arch/arm64/boot/
        
