name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc libncurses5-dev libssl-dev bison flex libelf-dev clang lld

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        make O=out fog-perf_defconfig
        make -j$(nproc --all) O=out ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android-

    - name: Upload Boot Image or Kernel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Kernel
        path: out/arch/arm64/boot/ Image.gz-dtb
        
